### ISSUE TITLE
Wrong 2.3.0-dev.7 tag

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry/device-snmp-go#186]
This repository has an unexpected [2.3.0-dev.7](https://github.com/edgexfoundry/device-snmp-go/releases/tag/2.3.0-dev.7) tag. The current last valid tag is [v2.2.1-dev.7](https://github.com/edgexfoundry/device-snmp-go/releases/tag/v2.2.1-dev.7), with a `v` prefix.

# 🐞 Bug Report

### Affected Services [**REQUIRED**]
Device SNMP

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v2.2.1-dev.7

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by farshidtz** [comment]
@ernestojeda please check as the tag is created by you.

**Comment by lenny-intel** [comment]
@ernestojeda , I run into similar issue trying to use latest go-mod tags that your script created. 
The one that was generated for Bootstrap in the pipeline for my PR merge after you re-generated the tags works fine.

**Comment by ernestojeda** [comment]
I have re-created the tag with the `v` prefix
